### ISSUE TITLE
Running tests fail because of incompatibility with @near-wallet-selector

### ISSUE THREAD

**Issue by spam0115** [keypom/keypom-js#5]
I'm trying to run the tests but it fails because of some incompatibility with @near-wallet-selector.  Was there a change to @near-wallet-selector to render it incompatible?

C:\s\keypom-api\node_modules\keypom-js>yarn test
yarn run v1.22.19
warning ..\..\package.json: License should be a valid SPDX license expression
$ yarn build && yarn ava
warning ..\..\package.json: License should be a valid SPDX license expression
$ npx tsc
src/lib/keypom-utils.ts:2:10 - error TS2305: Module '"@near-wallet-selector/core/lib/wallet"' has no exported member 'SignAndSendTransactionParams'.

2 import { SignAndSendTransactionParams, Transaction } from "@near-wallet-selector/core/lib/wallet";
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in src/lib/keypom-utils.ts:2

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by mattlockyer** [comment]
I don't think this was related to wallet-selector. Tests are all passing now.
